Repository Korako2/ISDB, pull requests merged in 2023-12, with the labels that each got.

#158 feat: order approval mechanism
  backend/src/main/kotlin/org/ifmo/isbdcurs/controllers/AdminController.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/models/data.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/models/responses.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/persistence/repositories.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/services/DriverService.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/services/OrderService.kt
  backend/src/main/resources/templates/admin.html
  backend/src/main/resources/templates/find_suitable_driver.html
  backend/src/main/resources/templates/suitable_driver.html
Labels: Ready for review

#167 feat: manager + customer notifications
  backend/src/main/kotlin/org/ifmo/isbdcurs/customer/ordering/OrderService.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/manager/OrderApprovalService.kt
  backend/src/main/resources/static/js/notifications.js
  backend/src/main/resources/templates/admin.html
  backend/src/main/resources/templates/customer/active_order_details.html
  backend/src/main/resources/templates/customer/completed_orders.html
  backend/src/main/resources/templates/customer/index.html
  backend/src/main/resources/templates/customer/ordering/address_form.html
  backend/src/main/resources/templates/customer/ordering/cargo_form.html
  backend/src/main/resources/templates/customer/ordering/submit_order.html
  backend/src/main/resources/templates/find_suitable_driver.html
  backend/src/main/resources/templates/fragments/general.html
  backend/src/main/resources/templates/suitable_driver.html
Labels: Ready for review

#172 Add headers and footers on the manager page
  backend/src/main/kotlin/org/ifmo/isbdcurs/controllers/AdminController.kt
  backend/src/main/resources/templates/admin.html
  backend/src/main/resources/templates/find_suitable_driver.html
  backend/src/main/resources/templates/suitable_driver.html
Labels: Ready for review

#173 feat: add a mechanism for approving and rejecting drivers
  backend/src/main/kotlin/org/ifmo/isbdcurs/controllers/AdminController.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/models/responses.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/persistence/repositories.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/services/DriverService.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/services/OrderService.kt
  backend/src/main/resources/templates/suitable_driver.html
Labels: Ready for review

#174 fix(customer): validation. Use var + @field: and more styles
  backend/src/main/kotlin/org/ifmo/isbdcurs/customer/OrderHelperService.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/customer/ordering/CostsService.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/customer/ordering/OrderService.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/customer/ordering/orderingControllers.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/manager/OrderApprovalService.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/models/data.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/services/OrderService.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/util/CostCalculator.kt
  backend/src/main/resources/templates/customer/active_order_details.html
  backend/src/main/resources/templates/customer/completed_orders.html
  backend/src/main/resources/templates/customer/ordering/address_form.html
  backend/src/main/resources/templates/customer/ordering/cargo_form.html
  backend/src/main/resources/templates/customer/ordering/submit_order.html
  backend/src/main/resources/templates/fragments/general.html
Labels: Draft

#176 feat: add reject order mechanism
  backend/src/main/kotlin/org/ifmo/isbdcurs/controllers/AdminController.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/manager/OrderApprovalService.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/persistence/repositories.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/services/OrderService.kt
  backend/src/main/resources/templates/admin.html
Labels: Ready for review

#177 new driver movement
  backend/sql/functions.sql
  backend/src/main/kotlin/org/ifmo/isbdcurs/controllers/AdminController.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/controllers/BusinessController.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/internal/DriverWorker.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/manager/OrderApprovalService.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/services/DriverService.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/services/OrderService.kt
Labels: WIP

#185 refactor: change date display
  backend/src/main/kotlin/org/ifmo/isbdcurs/services/DriverService.kt
  backend/src/main/resources/templates/suitable_driver.html
Labels: Ready for review

#186 Small code refactor
  backend/src/main/kotlin/org/ifmo/isbdcurs/controllers/LoginController.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/customer/CustomerController.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/customer/ordering/AddressService.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/customer/ordering/OrderService.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/services/DriverService.kt
  backend/src/main/kotlin/org/ifmo/isbdcurs/services/OrderService.kt
Labels: Ready for review
